### PR TITLE
Use "describe" blocks where appropriate

### PR DESCRIPTION
**Pull request by jzaleski**
Clean-up/re-organize the tests a bit by using "describe" blocks to section off the methods being tested

### CODE REVIEW

**Comment by jzaleski** [comment]
@dimko this is the last bit of clean-up I wanted to get out of the way before submitting a pull-request feature I have implemented.

**Comment by jzaleski** [comment]
Any update on this? What do you think of the changes @dimko?

**Comment by dmeremyanin** [comment]
Hi, sorry for delay.
95% of tests is copy-paste from the [valium](https://github.com/ernie/valium) project.
`value_of`, `values_of` is aliases for `pluck` method and, actually, all tests describe `pluck` method.

I think we should use `pluck` in tests and test that aliases is work separately.

**Comment by jzaleski** [comment]
@dimko just to be clear, none of the tests were changed in this pull-request, they were only re-organized and logically grouped (in "describe" blocks) by the methods they are testing on the subject. I felt this made the tests significantly easier to read/understand (and set a good precedent for future tests).

Even though I think this is probably fine as is (and _could_ be merged as a stepping-stone, regardless), I'm fine with giving it a more significant overhaul (if you think it's worth it).

**Pull request closed without merging**
